### ISSUE TITLE
Questions about parameter files

### ISSUE THREAD

**Issue by samsrabin** [AgMIP-GGCMI/cropCalendars#3]
(@minoli-pik Tagging you as requested, to ensure you see this.)

# crop_parameters.csv

1. These are these parameters that should be **shared** for all crop models, right?
2. Not every GGCMI crop is represented here. Does that mean that some crops, like `pea`, can't have outputs produced?
3. `maturity_to_harvest` and `max_flowering_phase` appear to be unused; is that correct?

# lpjml_crop_parameters_ggcmi_ph3.csv

1. These are parameters that should be **customized** for each crop model, right?
2. `photosens`, `basetemp2`, `basephoto`, and `fphu.ant` appear to be unused; is that correct?

**Comment by minoli-pik** [comment]
Hi @samsrabin,

## crop_parameters.csv
You are right:
1. `crop_parameters.csv` includes the parameters for the crop calendar calculation, which is not crop-model specific.
2. the crop-calendar model has been developed for
    a. grain crops only (i.e. root crops, like sugar beet can't be handled with the rules as they are currently)
    b. crops for which parameters have been found in literature. Yet, it could be eventually be extended to simulate other grain crops, such as `pea`. However for these crops, in the GGCMI calls we had decided to use the observation-based crop calendars and adapt only the cultivar (i.e. PHU), like we did in GGCMI phase 2 with the A1 adaptation scenario.
3. Correct, `maturity_to_harvest` and `max_flowering_phase` are not used for calculating crop calendars. `maturity_to_harvest` is, in principle, needed to evaluate the crop calendar results. In fact, the model simulates maturity dates, while observation based datasets report harvest dates. Therefore, if you want to compare the simulated with the observed harvest dates, you need to first add `maturity_to_harvest` to simulated maturity dates. Yet, `maturity_to_harvest` is very much approximate and values were taken from [Elliott et al., 2015](https://gmd.copernicus.org/articles/8/261/2015/).

## lpjml_crop_parameters_ggcmi_ph3.csv

1. Right!
2. Yes, in LPJmL simulations photoperiod responses are not considered, although parameters exist for that (`photosens`, `basephoto`). `basetemp2` and `fphu.ant` are not used for GGCMI simulations, and are rather left-overs from other approaches/projects.

**Comment by samsrabin** [comment]
Okay, that all makes sense. Thanks! I'll close this issue.
