### ISSUE TITLE
bin file read

### ISSUE THREAD

**Issue by lixuan-code** [AgMIP-GGCMI/cropCalendars#4]
Hello, it seems that the bin file is read in the model to get the latitude and longitude information of the study area, can you change the bin file to read the latitude and longitude of nc directly in R language without using the bin file of LPJml model?

`# ------------------------------------ #
# Read grid file
readGridLPJmL <- function(
  fname  = "/p/projects/lpjml/input/historical/input_VERSION2/grid.bin",
  ncells = NULL,
  header = NULL,
  nbands = NULL,
  dtype  = NULL,
  dsize  = NULL,
  scalar = NULL
  ) {

  print(paste("Reading grid.bin input:", fname))

  # check file size
  check.fs <- (file.size(fname) - header)/ncells/dsize == nbands
  print(paste("File size as expected = ", check.fs))

  # read out data
  fcon <- file(fname, open = "rb")
  seek(con = fcon, where = header, origin = "start")
  x <- array(NA, c(ncells, nbands))
  for (i in seq_len(ncells)) {
    x[i,] <- readBin(fcon, what = dtype, size = dsize , n = nbands)*scalar
  }
  close.connection(fcon)
  print(str(x))
  return(x)
}

grid_df <- as.data.frame(
  readGridLPJmL(
    ncells = 67420, header = 43, nbands = 2, dtype = integer(),
    dsize = 2, scalar = 0.01)
  )
names(grid_df) <- c("lon", "lat")
`

**Comment by cmueller-pik** [comment]
Feel free to suggest a technical implementation of that functionality

**Comment by lixuan-code** [comment]
Not all who use the model combine it with LPJml, so it seems that when config.R, you can run the model by reading the nc or shp latitude and longitude of the study area directly. But I don't know if this is possible.
